services:
  citas_api:
    build: .
    container_name: citas_api
    ports:
      - "4003:4003"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 4003 --reload
