services:
  clivet_db:
    image: postgres:latest
    container_name: clivet_db
    restart: always
    environment:
      POSTGRES_DB: clivet2025
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Clivet2025**++
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5430:5432"